spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentfeedback
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true

    locations:
      - classpath:db/migration
  messages:
    basename: i18n/messages
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}  
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

jwt:
  secret-key: Yr2kWrQdCiQcL1zdXeQadJxmS7iCnwn+z6Gj5c7DYX0=
  expiration-time: 86400
